# Run time Tomcat Env Image. 
FROM tomcat:8.0

MAINTAINER sathish <sathish,sambamurthy@mindtree.com>

#COPY target/petclinic.war  /usr/local/tomcat/webapps/
COPY target/petclinic.war  /opt/tomcat/webapps
